-- Supabase数据库表结构设置脚本
-- 请在Supabase项目的SQL编辑器中执行以下命令

-- 创建事件表
CREATE TABLE IF NOT EXISTS map_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type VARCHAR(50) NOT NULL CHECK (type IN ('accident', 'event', 'news', 'other')),
  location JSONB NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建用户扩展表（可选，用于存储额外用户信息）
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name VARCHAR(100),
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_map_events_user_id ON map_events(user_id);
CREATE INDEX IF NOT EXISTS idx_map_events_timestamp ON map_events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_map_events_type ON map_events(type);
CREATE INDEX IF NOT EXISTS idx_map_events_location ON map_events USING GIN(location);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 为事件表创建更新时间触发器
DROP TRIGGER IF EXISTS update_map_events_updated_at ON map_events;
CREATE TRIGGER update_map_events_updated_at 
    BEFORE UPDATE ON map_events 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 为用户表创建更新时间触发器
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON users 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 启用行级安全策略 (RLS)
ALTER TABLE map_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- 创建安全策略
-- 用户只能看到自己的事件，或者可以看到所有事件（根据需求调整）
CREATE POLICY "用户可以查看所有事件" ON map_events
    FOR SELECT USING (true);

CREATE POLICY "用户可以插入自己的事件" ON map_events
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户只能更新自己的事件" ON map_events
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户只能删除自己的事件" ON map_events
    FOR DELETE USING (auth.uid() = user_id);

-- 用户表策略
CREATE POLICY "用户可以查看自己的信息" ON users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "用户可以插入自己的信息" ON users
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "用户只能更新自己的信息" ON users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "用户只能删除自己的信息" ON users
    FOR DELETE USING (auth.uid() = id);

-- 创建新用户注册时自动创建用户记录的触发器
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, display_name)
  VALUES (new.id, new.raw_user_meta_data->>'display_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();