// 数据库初始化脚本 - 在浏览器控制台中运行
import { supabase, TABLES } from './src/supabase.js'

async function initializeDatabase() {
  try {
    console.log('开始初始化数据库...')
    
    // 创建事件表
    const { error: eventsError } = await supabase.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS ${TABLES.EVENTS} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title VARCHAR(255) NOT NULL,
          description TEXT NOT NULL,
          type VARCHAR(50) NOT NULL CHECK (type IN ('accident', 'event', 'news', 'other')),
          location JSONB NOT NULL,
          user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
          timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        ALTER TABLE ${TABLES.EVENTS} ENABLE ROW LEVEL SECURITY;
        
        CREATE POLICY IF NOT EXISTS "允许所有用户查看事件" ON ${TABLES.EVENTS}
          FOR SELECT USING (true);
        
        CREATE POLICY IF NOT EXISTS "用户只能插入自己的事件" ON ${TABLES.EVENTS}
          FOR INSERT WITH CHECK (auth.uid() = user_id);
        
        CREATE POLICY IF NOT EXISTS "用户只能更新自己的事件" ON ${TABLES.EVENTS}
          FOR UPDATE USING (auth.uid() = user_id);
        
        CREATE POLICY IF NOT EXISTS "用户只能删除自己的事件" ON ${TABLES.EVENTS}
          FOR DELETE USING (auth.uid() = user_id);
      `
    })
    
    if (eventsError) {
      console.error('创建事件表失败:', eventsError)
    } else {
      console.log('事件表创建成功')
    }
    
    console.log('数据库初始化完成！')
    return true
  } catch (error) {
    console.error('数据库初始化失败:', error)
    return false
  }
}

// 导出函数供控制台使用
window.initializeDatabase = initializeDatabase

console.log('数据库初始化脚本已加载！')
console.log('在控制台中运行: initializeDatabase()')