-- 快速修复脚本
-- 1. 确保表结构匹配（如果新结构未生效，使用简化版本）

-- 删除现有表（会丢失数据，仅用于测试）
DROP TABLE IF EXISTS map_events CASCADE;

-- 创建简化的表结构（与当前代码匹配）
CREATE TABLE map_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('accident', 'event', 'news', 'other')),
    location JSONB NOT NULL,
    user_id UUID NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建基本索引
CREATE INDEX ON map_events (user_id);
CREATE INDEX ON map_events ("timestamp" DESC);
CREATE INDEX ON map_events (type);
CREATE INDEX ON map_events USING GIN (location);

-- 插入测试数据
INSERT INTO map_events (title, description, type, location, user_id) VALUES 
('测试事件', '这是一个测试事件', 'event', '{"lat": 39.9042, "lng": 116.4074}', NULL),
('另一个事件', '另一个测试事件', 'news', '{"lat": 39.9142, "lng": 116.4174}', NULL);

-- 启用RLS（可选）
ALTER TABLE map_events ENABLE ROW LEVEL SECURITY;

-- 简化的策略（允许所有操作）
CREATE POLICY "allow_all" ON map_events FOR ALL USING (true);

COMMIT;