-- 更新事件表结构到新的设计
-- 这个脚本会将现有的UUID ID改为自增主键，并添加新的索引

-- 1. 备份现有数据
CREATE TABLE IF NOT EXISTS map_events_backup AS SELECT * FROM map_events;

-- 2. 删除现有的表
DROP TABLE IF EXISTS map_events CASCADE;

-- 3. 创建新的事件表（使用自增ID）
CREATE TABLE map_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    location JSONB NOT NULL,
    user_id UUID NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
    CONSTRAINT map_events_pkey PRIMARY KEY (id),
    CONSTRAINT map_events_type_check CHECK (
        type = ANY (
            ARRAY['accident'::VARCHAR, 'event'::VARCHAR, 'news'::VARCHAR, 'other'::VARCHAR]
        )
    )
) TABLESPACE pg_default;

-- 4. 恢复数据（映射UUID到新的自增ID）
INSERT INTO map_events (title, description, type, location, user_id, timestamp, created_at, updated_at)
SELECT 
    title, 
    description, 
    type, 
    location, 
    user_id,
    timestamp,
    created_at,
    updated_at
FROM map_events_backup;

-- 5. 创建新的索引
CREATE INDEX IF NOT EXISTS idx_map_events_user_id ON map_events USING BTREE (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_map_events_timestamp ON map_events USING BTREE ("timestamp" DESC) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_map_events_type ON map_events USING BTREE (type) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_map_events_location ON map_events USING GIN (location) TABLESPACE pg_default;

-- 6. 创建更新触发器
CREATE TRIGGER update_map_events_updated_at 
    BEFORE UPDATE ON map_events 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 7. 启用行级安全策略
ALTER TABLE map_events ENABLE ROW LEVEL SECURITY;

-- 8. 创建策略
CREATE POLICY "允许查看所有事件" ON map_events
    FOR SELECT USING (true);

CREATE POLICY "用户只能管理自己的事件" ON map_events
    FOR ALL USING (auth.uid() = user_id);

-- 9. 清理备份表（如果确认迁移成功，可以删除）
-- DROP TABLE IF EXISTS map_events_backup;

COMMIT;